# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "sinatra", require: "sinatra/base"
gem "puma"
gem "virtus"
gem "faraday"
gem "dotenv"
gem "colorize"
gem "pry"
gem "concurrent-ruby", require: "concurrent"
